#!/usr/bin/env python3
"""
Compute coefficients for 1/r potential multipole expansion in z=0 plane
Using spherical harmonics expansion restricted to equatorial plane
"""

import numpy as np
from scipy.special import lpmv, factorial
import sys
import os


def compute_solid_harmonics_coefficients(p_max):
    """
    For 1/r potential in z=0 plane:
    1/|r-r'| = sum_{n=0}^{p_max} sum_{m=-n}^{n} C_n^m(r') / r^(n+1) * Y_n^m(theta, phi)

    For z=0 plane (theta = pi/2), we only need Y_n^m(pi/2, phi) = P_n^m(0) * e^(i*m*phi)

    Returns normalization factors and Legendre values at theta=pi/2
    """

    # Normalization constants for real solid harmonics
    # K_n^m = sqrt((2n+1) * (n-|m|)! / (4*pi * (n+|m|)!))
    K_nm = np.zeros((p_max + 1, 2*p_max + 1))

    # Associated Legendre polynomials at mu=0 (theta=pi/2)
    P_nm_equator = np.zeros((p_max + 1, 2*p_max + 1))

    for n in range(p_max + 1):
        for m_idx, m in enumerate(range(-n, n + 1)):
            m_abs = abs(m)

            # Normalization constant
            if n >= m_abs:
                K_nm[n, m_idx] = np.sqrt(
                    (2*n + 1) * factorial(n - m_abs) / (4 * np.pi * factorial(n + m_abs))
                )

                # P_n^m(0) - many are zero!
                # P_n^m(0) ≠ 0 only if n-m is even and m_abs <= n
                if (n - m_abs) % 2 == 0:
                    P_nm_equator[n, m_idx] = lpmv(m_abs, n, 0.0)
                else:
                    P_nm_equator[n, m_idx] = 0.0

    return K_nm, P_nm_equator


def compute_binomial_coefficients(p_max):
    """
    Compute binomial coefficients C(n,k) for multipole translation
    """
    binom = np.zeros((2*p_max + 1, 2*p_max + 1))

    for n in range(2*p_max + 1):
        for k in range(n + 1):
            binom[n, k] = factorial(n) / (factorial(k) * factorial(n - k))

    return binom


def compute_factorial_table(p_max):
    """
    Precompute factorials up to (2*p_max)!
    """
    max_n = 2 * p_max + 10
    fact_table = np.zeros(max_n)

    for n in range(max_n):
        fact_table[n] = factorial(n)

    return fact_table


def compute_anm_coefficients(p_max):
    """
    Compute A_n^m coefficients for M2L translation:
    A_n^m = (-1)^n / sqrt((n-m)! * (n+m)!)
    """
    A_nm = np.zeros((p_max + 1, 2*p_max + 1))

    for n in range(p_max + 1):
        for m_idx, m in enumerate(range(-n, n + 1)):
            m_abs = abs(m)
            if n >= m_abs:
                A_nm[n, m_idx] = (-1)**n / np.sqrt(
                    factorial(n - m_abs) * factorial(n + m_abs)
                )

    return A_nm


def write_fortran_module(filename, p_max, K_nm, P_nm_equator, factorial_table, A_nm, binom):
    """
    Write precomputed coefficients as Fortran module
    """

    with open(filename, 'w') as f:
        f.write(f"module multipole_coefficients\n")
        f.write(f"  ! Precomputed coefficients for 1/r potential (z=0 plane)\n")
        f.write(f"  ! Generated by compute_coefficients.py\n")
        f.write(f"  ! Maximum expansion order: p_max = {p_max}\n")
        f.write(f"  implicit none\n")
        f.write(f"  integer, parameter :: dp = selected_real_kind(15, 307)\n")
        f.write(f"  integer, parameter :: P_MAX_COEFF = {p_max}\n\n")

        # Write factorial table
        f.write(f"  ! Factorial table: 0! to {len(factorial_table)-1}!\n")
        f.write(f"  real(dp), parameter :: FACTORIAL({len(factorial_table)}) = [ &\n")
        for i in range(len(factorial_table)):
            f.write(f"    {factorial_table[i]:.16e}_dp")
            if i < len(factorial_table) - 1:
                f.write(", &\n")
            else:
                f.write(" ]\n\n")

        # Write K_nm normalization constants (only non-zero values)
        f.write(f"  ! Normalization constants K_n^m for spherical harmonics\n")
        f.write(f"  ! K_nm(m+n+1, n+1) for n=0..{p_max}, m=-n..n\n")
        f.write(f"  real(dp), parameter :: K_NM(0:{2*p_max}, 0:{p_max}) = reshape([ &\n")

        count = 0
        for n in range(p_max + 1):
            for m_idx in range(2*p_max + 1):
                if m_idx < 2*n + 1:
                    f.write(f"    {K_nm[n, m_idx]:.16e}_dp")
                else:
                    f.write(f"    0.0_dp")

                count += 1
                if count < (p_max + 1) * (2*p_max + 1):
                    f.write(", &\n")
                else:
                    f.write(" ], &\n")

        f.write(f"    shape=[{2*p_max + 1}, {p_max + 1}])\n\n")

        # Write P_n^m(0) values at equator
        f.write(f"  ! Associated Legendre polynomials at theta=pi/2: P_n^m(0)\n")
        f.write(f"  ! P_NM_EQUATOR(m+n+1, n+1) for n=0..{p_max}, m=-n..n\n")
        f.write(f"  real(dp), parameter :: P_NM_EQUATOR(0:{2*p_max}, 0:{p_max}) = reshape([ &\n")

        count = 0
        for n in range(p_max + 1):
            for m_idx in range(2*p_max + 1):
                if m_idx < 2*n + 1:
                    f.write(f"    {P_nm_equator[n, m_idx]:.16e}_dp")
                else:
                    f.write(f"    0.0_dp")

                count += 1
                if count < (p_max + 1) * (2*p_max + 1):
                    f.write(", &\n")
                else:
                    f.write(" ], &\n")

        f.write(f"    shape=[{2*p_max + 1}, {p_max + 1}])\n\n")

        f.write(f"end module multipole_coefficients\n")

    print(f"Fortran module written to {filename}")


def write_binary_coefficients(filename, p_max, K_nm, P_nm_equator, factorial_table, A_nm, binom):
    """
    Write coefficients in binary format for faster loading
    """
    np.savez_compressed(filename,
                       p_max=p_max,
                       K_nm=K_nm,
                       P_nm_equator=P_nm_equator,
                       factorial_table=factorial_table,
                       A_nm=A_nm,
                       binom=binom)

    print(f"Binary coefficients saved to {filename}")


def main():
    """
    Main function - compute and save all coefficients
    """

    if len(sys.argv) > 1:
        p_max = int(sys.argv[1])
    else:
        p_max = 20  # Default maximum order

    print(f"Computing coefficients for 1/r potential (z=0 plane)")
    print(f"Maximum expansion order: p_max = {p_max}")
    print("")

    # Compute all coefficients
    print("Computing spherical harmonics coefficients...")
    K_nm, P_nm_equator = compute_solid_harmonics_coefficients(p_max)

    print("Computing factorial table...")
    factorial_table = compute_factorial_table(p_max)

    print("Computing A_nm coefficients...")
    A_nm = compute_anm_coefficients(p_max)

    print("Computing binomial coefficients...")
    binom = compute_binomial_coefficients(p_max)

    print("")

    # Write to files
    os.makedirs('coefficients', exist_ok=True)

    fortran_file = f'coefficients/multipole_coefficients_p{p_max}.f90'
    binary_file = f'coefficients/multipole_coefficients_p{p_max}.npz'

    write_fortran_module(fortran_file, p_max, K_nm, P_nm_equator,
                        factorial_table, A_nm, binom)

    write_binary_coefficients(binary_file, p_max, K_nm, P_nm_equator,
                             factorial_table, A_nm, binom)

    print("")
    print("Done!")
    print(f"Use in Fortran: use multipole_coefficients")
    print(f"Use in Python: np.load('{binary_file}')")


if __name__ == '__main__':
    main()
